export const oldPodcastPathsMap = [
  [
    '01_02_react-hooks-que-son-vale-la-pena-el-hype',
    '01_02_react-hooks'
  ],
  [
    '01_03_edge-usara-chromium-como-motor-en-su-navegador-buenas-o-malas-noticias',
    '01_03_edge-usara-chromium-buenas-o-malas-noticias'
  ],
  [
    '01_04_lo-mejor-de-2018-en-el-frontend-y-lo-que-nos-espera-en-2019',
    '01_04_lo-mejor-de-2018-en-la-programacion-web'
  ],
  [
    '01_05_lo-mejor-de-2018-en-el-frontend-y-lo-que-nos-espera-en-2019-parte-ii',
    '01_05_lo-mejor-de-2018-en-la-programacion-web'
  ],
  [
    '01_06_la-gran-brecha-del-frontend-hay-una-crisis-de-identidad-en-el-mundillo-del-desarrollo-web',
    '01_06_la-gran-brecha-en-el-mundo-del-frontend'
  ],
  [
    '01_07_consejos-ideas-y-practicas-para-ser-mejor-desarrollador',
    '01_07_consejos-ideas-practicas-para-mejorar-como-desarrollador'
  ],
  [
    '01_08_experiencia-bootcamp-que-se-siente-al-cambiar-tu-vida-para-aprender-programacion',
    '01_08_experiencia-bootcamp-escuelas-de-programacion'
  ],
  [
    '01_09_microfrontends-que-son-que-ventajas-y-desventajas-tienen',
    '01_09_microfrontends-que-son-ventajas-desventajas'
  ],
  [
    '01_10_consejos-y-experiencias-sobre-entrevistas-de-trabajo-en-tecnologia',
    '01_10_entrevistas-de-trabajo-en-programacion'
  ],
  [
    '01_11_hay-que-poner-internet-a-dieta-que-es-un-ux-engineer',
    '01_11_internet-a-dieta-ux-engineer'
  ],
  [
    '01_12_que-son-los-ingenieros-10x-css-camp-y-js-camp-2019',
    '01_12_que-es-10x-engineer'
  ],
  [
    '01_13_como-hacemos-sostenible-el-codigo-abierto-tendriamos-que-pagar-por-el',
    '01_13_como-mantenemos-el-codigo-abierto'
  ],
  [
    '02_01_tc-39-presente-y-futuro-del-javascript',
    '02_01_tc93-presente-y-futuro-de-javascript'
  ],
  [
    '02_02_trabajo-en-remoto-y-equipos-distribuidos',
    '02_02_trabajo_remoto_equipos_distribuidos'
  ]
]
